<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <Version>1.0.4</Version>
	  <ApplicationIcon>Image.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image.ico" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Image.ico">
      <CopyToOutputDirectory><Image Width="18" Height="18" Margin="0,0,8,0" VerticalAlignment="Center" Stretch="Uniform" Source="/Image.ico" /></CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
